import type { DashboardRequest } from "@/lib/requests";

const now = Date.now();

/* Sample request data used to populate the dashboard UI during development. */
export const mockSongRequests: DashboardRequest[] = [
  {
    id: "req_1",
    title: "Levitating",
    artist: "Dua Lipa",
    requesterName: "Sarah M.",
    message: "Birthday girl wants this next!",
    paidAmount: 5,
    submittedAt: new Date(now - 5 * 60 * 1000).toISOString(),
    status: "pending",
    priorityScore: 98,
    bpm: 103,
    key: "Bbm",
  },
  {
    id: "req_2",
    title: "Blinding Lights",
    artist: "The Weeknd",
    requesterName: "Mike R.",
    paidAmount: 3,
    submittedAt: new Date(now - 8 * 60 * 1000).toISOString(),
    status: "pending",
    priorityScore: 92,
    bpm: 171,
    key: "F#m",
  },
  {
    id: "req_3",
    title: "Don't Start Now",
    artist: "Dua Lipa",
    requesterName: "Jessica T.",
    message: "Love this one!",
    paidAmount: null,
    submittedAt: new Date(now - 12 * 60 * 1000).toISOString(),
    status: "pending",
    priorityScore: 80,
    bpm: 124,
    key: "Am",
  },
  {
    id: "req_4",
    title: "As It Was",
    artist: "Harry Styles",
    requesterName: "Alex K.",
    paidAmount: null,
    submittedAt: new Date(now - 15 * 60 * 1000).toISOString(),
    status: "pending",
    priorityScore: 76,
    bpm: 174,
    key: "A",
  },
  {
    id: "req_5",
    title: "One Kiss",
    artist: "Calvin Harris & Dua Lipa",
    requesterName: "Nia B.",
    paidAmount: 7,
    submittedAt: new Date(now - 18 * 60 * 1000).toISOString(),
    status: "seen",
    priorityScore: 96,
    bpm: 124,
    key: "Em",
  },
  {
    id: "req_6",
    title: "Cruel Summer",
    artist: "Taylor Swift",
    requesterName: "Chris D.",
    message: "Crowd will scream this.",
    paidAmount: null,
    submittedAt: new Date(now - 24 * 60 * 1000).toISOString(),
    status: "played",
    priorityScore: 71,
    bpm: 170,
    key: "A",
  },
];
